import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const toAbsolute = (p: string) => path.resolve(__dirname, p);

const indexFile = fs.createWriteStream(toAbsolute("src/pages.ts"));
function toPascalCase(str: string) {
  return str
    .replace(/([a-z])([A-Z])/g, "$1 $2") // Splits camelCase words into separate words
    .replace(/[-_]+|[^\p{L}\p{N}]/gu, " ") // Replaces dashes, underscores, and special characters with spaces
    .toLowerCase() // Converts the entire string to lowercase
    .replace(/(?:^|\s)(\p{L})/gu, (_, letter) => letter.toUpperCase()) // Capitalizes the first letter of each word
    .replace(/\s+/g, ""); // Removes all spaces
}

const pages = fs
  .readdirSync(toAbsolute("src/pages"))
  .filter((file) => file.endsWith(".mdx"));

pages.sort();

const names = pages.map((page) => {
  const name = path.basename(page, ".mdx");
  return {
    file: `./pages/${page}`,
    name,
    imp: `Imp${toPascalCase(name)}`,
  };
});

indexFile.write(`// This file is auto-generated by \`bun run codegen\`
// Do not edit this file directly

import type { ComponentType } from "react";
`);

for (const { imp, file } of names) {
  indexFile.write(`import * as ${imp} from "${file}";\n`);
}

indexFile.write(`
export type MDXPageModule = {
  default: ComponentType;
  title?: string;
  grade?: number;
  subject?: string;
  format?: string;
  topic?: string;
};
`);

indexFile.write(`\n`);
indexFile.write(
  `export const pages: { name: string; imp: MDXPageModule }[] = [\n`,
);

for (const { imp, name } of names) {
  indexFile.write(`  { name: "${name}", imp: ${imp} },\n`);
}

indexFile.write(`];\n`);
indexFile.end();

console.log("Generated src/pages/index.ts");
