// This file is auto-generated by `bun run codegen`
// Do not edit this file directly

import type { ComponentType } from "react";
import * as ImpChemieAtomeLernkarten from "./pages/chemie-atome-lernkarten.mdx";
import * as ImpChemieAtomeQuiz from "./pages/chemie-atome-quiz.mdx";
import * as ImpChemieAtome from "./pages/chemie-atome.mdx";
import * as ImpChemieElementeQuiz1 from "./pages/chemie-elemente-quiz-1.mdx";
import * as ImpChemieElementeQuiz2 from "./pages/chemie-elemente-quiz-2.mdx";
import * as ImpChemieElementeTabellen from "./pages/chemie-elemente-tabellen.mdx";
import * as ImpChemiePeriodensystemLernkarten from "./pages/chemie-periodensystem-lernkarten.mdx";
import * as ImpChemiePeriodensystemQuiz from "./pages/chemie-periodensystem-quiz.mdx";
import * as ImpChemiePeriodensystem from "./pages/chemie-periodensystem.mdx";
import * as ImpChemieVerbindungenLernkarten from "./pages/chemie-verbindungen-lernkarten.mdx";
import * as ImpChemieVerbindungenQuiz from "./pages/chemie-verbindungen-quiz.mdx";
import * as ImpChemieVerbindungen from "./pages/chemie-verbindungen.mdx";
import * as ImpGleichungen from "./pages/gleichungen.mdx";
import * as ImpHome from "./pages/home.mdx";
import * as ImpLupenWirkungLernkarten from "./pages/lupen-wirkung-lernkarten.mdx";
import * as ImpLupenWirkungQuiz from "./pages/lupen-wirkung-quiz.mdx";
import * as ImpLupenWirkung from "./pages/lupen-wirkung.mdx";
import * as ImpMatheSchularbeit2 from "./pages/mathe-schularbeit-2.mdx";
import * as ImpMatheTraining1 from "./pages/mathe-training-1.mdx";
import * as ImpMsFormsExample from "./pages/ms-forms-example.mdx";
import * as ImpPotenzschreibweise from "./pages/potenzschreibweise.mdx";
import * as ImpTerme from "./pages/terme.mdx";

export type MDXPageModule = {
  default: ComponentType;
  title?: string;
  grade?: number;
  subject?: string;
  format?: string;
  topic?: string;
};

export const pages: { name: string; imp: MDXPageModule }[] = [
  { name: "chemie-atome-lernkarten", imp: ImpChemieAtomeLernkarten },
  { name: "chemie-atome-quiz", imp: ImpChemieAtomeQuiz },
  { name: "chemie-atome", imp: ImpChemieAtome },
  { name: "chemie-elemente-quiz-1", imp: ImpChemieElementeQuiz1 },
  { name: "chemie-elemente-quiz-2", imp: ImpChemieElementeQuiz2 },
  { name: "chemie-elemente-tabellen", imp: ImpChemieElementeTabellen },
  { name: "chemie-periodensystem-lernkarten", imp: ImpChemiePeriodensystemLernkarten },
  { name: "chemie-periodensystem-quiz", imp: ImpChemiePeriodensystemQuiz },
  { name: "chemie-periodensystem", imp: ImpChemiePeriodensystem },
  { name: "chemie-verbindungen-lernkarten", imp: ImpChemieVerbindungenLernkarten },
  { name: "chemie-verbindungen-quiz", imp: ImpChemieVerbindungenQuiz },
  { name: "chemie-verbindungen", imp: ImpChemieVerbindungen },
  { name: "gleichungen", imp: ImpGleichungen },
  { name: "home", imp: ImpHome },
  { name: "lupen-wirkung-lernkarten", imp: ImpLupenWirkungLernkarten },
  { name: "lupen-wirkung-quiz", imp: ImpLupenWirkungQuiz },
  { name: "lupen-wirkung", imp: ImpLupenWirkung },
  { name: "mathe-schularbeit-2", imp: ImpMatheSchularbeit2 },
  { name: "mathe-training-1", imp: ImpMatheTraining1 },
  { name: "ms-forms-example", imp: ImpMsFormsExample },
  { name: "potenzschreibweise", imp: ImpPotenzschreibweise },
  { name: "terme", imp: ImpTerme },
];
