// This file is auto-generated by `bun run codegen`
// Do not edit this file directly

import type { ComponentType } from "react";
import * as ImpChemieAtomeLernkarten from "./pages/chemie-atome-lernkarten.mdx";
import * as ImpChemieAtomeQuiz from "./pages/chemie-atome-quiz.mdx";
import * as ImpChemieAtome from "./pages/chemie-atome.mdx";
import * as ImpChemieElementeTabellen from "./pages/chemie-elemente-tabellen.mdx";
import * as ImpChemiePeriodensystemLernkarten from "./pages/chemie-periodensystem-lernkarten.mdx";
import * as ImpChemiePeriodensystemQuiz from "./pages/chemie-periodensystem-quiz.mdx";
import * as ImpChemiePeriodensystem from "./pages/chemie-periodensystem.mdx";
import * as ImpChemieVerbindungenLernkarten from "./pages/chemie-verbindungen-lernkarten.mdx";
import * as ImpChemieVerbindungenQuiz from "./pages/chemie-verbindungen-quiz.mdx";
import * as ImpChemieVerbindungen from "./pages/chemie-verbindungen.mdx";
import * as ImpHome from "./pages/home.mdx";
import * as ImpMatheGleichungen from "./pages/mathe-gleichungen.mdx";
import * as ImpMathePotenzschreibweise from "./pages/mathe-potenzschreibweise.mdx";
import * as ImpMatheSchularbeit2Training from "./pages/mathe-schularbeit-2-training.mdx";
import * as ImpMatheSchularbeit2 from "./pages/mathe-schularbeit-2.mdx";
import * as ImpMatheTerme from "./pages/mathe-terme.mdx";
import * as ImpMsFormsExample from "./pages/ms-forms-example.mdx";
import * as ImpPhysikLupenWirkungLernkarten from "./pages/physik-lupen-wirkung-lernkarten.mdx";
import * as ImpPhysikLupenWirkungQuiz from "./pages/physik-lupen-wirkung-quiz.mdx";
import * as ImpPhysikLupenWirkung from "./pages/physik-lupen-wirkung.mdx";

export type MDXPageModule = {
  default: ComponentType;
  title?: string;
  grade?: number;
  subject?: string;
  format?: string;
  topic?: string;
};

export const pages: { name: string; imp: MDXPageModule }[] = [
  { name: "chemie-atome-lernkarten", imp: ImpChemieAtomeLernkarten },
  { name: "chemie-atome-quiz", imp: ImpChemieAtomeQuiz },
  { name: "chemie-atome", imp: ImpChemieAtome },
  { name: "chemie-elemente-tabellen", imp: ImpChemieElementeTabellen },
  { name: "chemie-periodensystem-lernkarten", imp: ImpChemiePeriodensystemLernkarten },
  { name: "chemie-periodensystem-quiz", imp: ImpChemiePeriodensystemQuiz },
  { name: "chemie-periodensystem", imp: ImpChemiePeriodensystem },
  { name: "chemie-verbindungen-lernkarten", imp: ImpChemieVerbindungenLernkarten },
  { name: "chemie-verbindungen-quiz", imp: ImpChemieVerbindungenQuiz },
  { name: "chemie-verbindungen", imp: ImpChemieVerbindungen },
  { name: "home", imp: ImpHome },
  { name: "mathe-gleichungen", imp: ImpMatheGleichungen },
  { name: "mathe-potenzschreibweise", imp: ImpMathePotenzschreibweise },
  { name: "mathe-schularbeit-2-training", imp: ImpMatheSchularbeit2Training },
  { name: "mathe-schularbeit-2", imp: ImpMatheSchularbeit2 },
  { name: "mathe-terme", imp: ImpMatheTerme },
  { name: "ms-forms-example", imp: ImpMsFormsExample },
  { name: "physik-lupen-wirkung-lernkarten", imp: ImpPhysikLupenWirkungLernkarten },
  { name: "physik-lupen-wirkung-quiz", imp: ImpPhysikLupenWirkungQuiz },
  { name: "physik-lupen-wirkung", imp: ImpPhysikLupenWirkung },
];
