// This file is auto-generated by `bun run codegen`
// Do not edit this file directly

import type { ComponentType } from "react";
import * as ImpHome from "./pages/home.mdx";
import * as ImpMatheSchularbeit1 from "./pages/mathe-schularbeit-1.mdx";
import * as ImpTerme from "./pages/terme.mdx";
import * as ImpPotenzschreibweise from "./pages/potenzschreibweise.mdx";
import * as ImpGleichungen from "./pages/gleichungen.mdx";

export type MDXPageModule = {
  default: ComponentType;
  title?: string;
  grade?: number;
  subject?: string;
};

export const pages: { name: string; imp: MDXPageModule }[] = [
  { name: "home", imp: ImpHome },
  { name: "mathe-schularbeit-1", imp: ImpMatheSchularbeit1 },
  { name: "terme", imp: ImpTerme },
  { name: "potenzschreibweise", imp: ImpPotenzschreibweise },
  { name: "gleichungen", imp: ImpGleichungen },
];
